### PR TITLE
Fix pyaff to integrate with automake better

### PR DESCRIPTION
**Pull request by umireon**
This PR will fix pyaff to build with [VPATH builds](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html) and sandboxed builds such as in [Homebrew](https://github.com/Homebrew/homebrew-core/pull/8315#issuecomment-269794666).

## Changes
* pyaff will build during automake's build phase.
* Public headers were moved into `include`: This change is necessary to build pyaff during automake's build phase.

### CODE REVIEW

**Comment by sshock** [comment]
Looks good as far as I can tell.  Do you have any more commits coming, or will it just be these three?

**Comment by umireon** [comment]
These three commits are all, thanks 🏁

**Comment by sshock** [comment]
@umireon Do you need me to create a new release?

**Comment by umireon** [comment]
Thank you for your kindness.
Yes, a new release is needed for Homebrew.

**Comment by sshock** [comment]
Ok, I made a new release: https://github.com/sshock/AFFLIBv3/releases/tag/v3.7.15

**Pull request merged**
